[package]
name = "api-server"
version = "0.1.0"
edition = "2021"


[[bin]]
name = "api-server"
path = "src/main.rs"

[dependencies]
actix-web = "4.0"
serde = {version = "1.0" , features = ["derive"]}
serde_json = "1.0"
uuid = {version = "1.0" , features = ["serde","v4"]}
